"""Generate TypeScript from Pydantic's serialization contract; --check detects drift."""
import json
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from app.engine.models import AnalysisResult
from app.api.routes import PortfolioRecord, JobRecord


def ts(schema):
    if '$ref' in schema: return schema['$ref'].split('/')[-1]
    if 'anyOf' in schema: return ' | '.join(ts(x) for x in schema['anyOf'])
    if 'enum' in schema: return ' | '.join(json.dumps(x) for x in schema['enum'])
    if 'const' in schema: return json.dumps(schema['const'])
    kind=schema.get('type')
    if kind in {'number','integer'}: return 'number'
    if kind=='boolean': return 'boolean'
    if kind=='string': return 'string'
    if kind=='null': return 'null'
    if kind=='array': return f'Array<{ts(schema["items"])}>'
    if kind=='object':
        if 'properties' in schema:
            return '{\n' + '\n'.join(f'  {json.dumps(k)}: {ts(v)};' for k,v in schema['properties'].items()) + '\n}'
        return 'Record<string, '+ts(schema.get('additionalProperties',{}))+'>'
    return 'unknown'


def main():
    definitions={}
    for model in [AnalysisResult,PortfolioRecord,JobRecord]:
        schema=model.model_json_schema(mode='serialization')
        definitions.update(schema.pop('$defs',{}))
        definitions[model.__name__]=schema
    output='// Generated by backend/scripts/generate_types.py. Do not edit.\n' + '\n\n'.join(f'export type {name} = {ts(schema)};' for name,schema in sorted(definitions.items())) + '\n'
    path=Path(__file__).resolve().parents[2]/'frontend/src/types/api.generated.ts'
    if '--check' in sys.argv:
        if not path.exists() or path.read_text(encoding='utf-8')!=output: raise SystemExit('API types are stale. Run generate_types.py.')
    else: path.write_text(output,encoding='utf-8')


if __name__=='__main__': main()
