// Generated by backend/scripts/generate_types.py. Do not edit.
export type AnalysisResult = {
  "model_version": string;
  "input_hash": string;
  "generated_at": string;
  "input": PortfolioInput;
  "scenario_comparison": ScenarioComparison;
  "methodology": Array<string>;
};

export type AnnualPrice = {
  "year": number;
  "price_per_unit": number;
};

export type Basin = "permian_delaware" | "permian_midland" | "eagle_ford_oil" | "eagle_ford_gas" | "bakken" | "dj_niobrara" | "gom_shelf" | "gom_deepwater" | "marcellus_utica" | "haynesville" | "scoop_stack" | "powder_river" | "montney" | "generic_onshore_us";

export type BinData = {
  "bin_start": number;
  "bin_end": number;
  "frequency": number;
};

export type CommodityPriceScenario = {
  "scenario_name": string;
  "oil_price_deck": Array<AnnualPrice>;
  "gas_price_deck": Array<AnnualPrice>;
  "ngl_price_deck": Array<AnnualPrice> | null;
  "price_volatility": number;
  "price_correlation_oil_gas": number;
};

export type DecisionComparison = {
  "prospect_id": string;
  "options": Record<string, DecisionMetrics>;
  "recommendation": DecisionType;
};

export type DecisionMetrics = {
  "decision_type": DecisionType;
  "expected_npv": number;
  "capital_required": number;
  "probability_positive_npv": number;
  "capital_efficiency": number;
};

export type DecisionOption = {
  "decision_type": DecisionType;
  "partner_carry_pct": number | null;
  "retained_working_interest": number | null;
  "promoted_interest": number | null;
  "expected_sale_price": number | null;
  "probability_of_closing": number | null;
  "holding_cost_per_year": number | null;
  "lease_expiry_risk": boolean | null;
};

export type DecisionType = "drill" | "farm_out" | "divest" | "defer";

export type DeclineParameters = {
  "initial_production_rate": number;
  "initial_decline_rate": number;
  "b_factor": number;
  "terminal_decline_rate": number;
  "well_life_years": number;
};

export type DistributionParams = {
  "base": number;
  "low": number;
  "high": number;
  "distribution_type": "triangular" | "lognormal";
};

export type DistributionSummary = {
  "mean": number;
  "std": number;
  "p10": number;
  "p50": number;
  "p90": number;
  "min": number;
  "max": number;
};

export type FrontierPoint = {
  "expected_npv": number;
  "portfolio_risk": number;
  "allocation": Record<string, DecisionType>;
  "capital_deployed": number;
  "capital_remaining": number;
  "expected_loss": number;
  "probability_of_loss": number;
  "cvar90_loss": number;
  "binding_constraints": Array<string>;
};

export type HydrocarbonType = "oil" | "gas" | "condensate" | "mixed";

export type JobRecord = {
  "id": string;
  "portfolio_id": string;
  "input_hash": string;
  "model_version": string;
  "status": string;
  "progress": number;
  "message": string;
  "error_code": string | null;
  "created": number;
  "updated": number;
};

export type PortfolioConstraints = {
  "min_prospects_drilled": number | null;
  "max_prospects_drilled": number | null;
  "mandatory_drill": Array<string> | null;
  "mandatory_defer": Array<string> | null;
  "max_single_prospect_pct_of_budget": number | null;
  "min_basin_allocation": Record<string, number> | null;
  "fixed_decisions": Record<string, DecisionType>;
};

export type PortfolioInput = {
  "prospects": Array<Prospect>;
  "decisions": Record<string, DecisionOption> | null;
  "capital_budget": number;
  "discount_rate": number;
  "simulation_iterations": number;
  "price_scenarios": Array<CommodityPriceScenario>;
  "random_seed": number;
  "risk_aversion": number;
  "name": string;
  "constraints": PortfolioConstraints;
};

export type PortfolioOptimizationResult = {
  "efficient_frontier": Array<FrontierPoint>;
  "recommended_portfolio": FrontierPoint;
  "current_portfolio": FrontierPoint | null;
  "prospect_robustness": Record<string, Record<string, DecisionType>>;
  "total_portfolio_npv_distribution": DistributionSummary;
  "diversification_benefit": number;
  "risk_measure": string;
  "risk_aversion": number;
  "solver_status": string;
};

export type PortfolioRecord = {
  "id": string;
  "name": string;
  "input": PortfolioInput;
  "revision": number;
  "updated": number;
};

export type Prospect = {
  "prospect_id": string;
  "name": string;
  "latitude": number;
  "longitude": number;
  "basin": Basin;
  "hydrocarbon_type": HydrocarbonType;
  "water_depth_ft": number | null;
  "resource_estimate": ResourceDistribution;
  "recovery_factor": DistributionParams;
  "well_cost": DistributionParams;
  "completion_cost": DistributionParams;
  "facility_cost": number;
  "opex_per_boe": DistributionParams;
  "royalty_rate": number;
  "tax_rate": number;
  "working_interest": number;
  "net_revenue_interest": number | null;
  "decline_params": DeclineParameters;
  "infrastructure_distance_miles": number | null;
  "lease_expiry_years": number | null;
  "notes": string | null;
  "assumption_source": string;
  "oil_fraction": number;
};

export type ProspectResult = {
  "prospect_id": string;
  "simulation": SimulationResult;
  "decision_comparison": DecisionComparison;
  "tornado": TornadoResult;
};

export type ResourceDistribution = {
  "p10": number;
  "p50": number;
  "p90": number;
  "distribution_type": "lognormal";
  "unit": "MBOE" | "MMBOE" | "MBO" | "MMBO" | "BOE" | "BO" | "MCF" | "BCF";
};

export type ScenarioComparison = {
  "scenario_results": Array<ScenarioResult>;
  "robust_prospects": Array<string>;
  "fragile_prospects": Array<string>;
};

export type ScenarioResult = {
  "scenario_name": string;
  "optimization_result": PortfolioOptimizationResult;
  "prospect_results": Array<ProspectResult>;
};

export type SensitivityItem = {
  "variable_name": string;
  "low_case_value": number;
  "low_case_npv": number;
  "high_case_value": number;
  "high_case_npv": number;
  "swing": number;
};

export type SimulationResult = {
  "prospect_id": string;
  "n_iterations": number;
  "npv_distribution": DistributionSummary;
  "irr_distribution": DistributionSummary | null;
  "payout_distribution": DistributionSummary | null;
  "probability_positive_npv": number;
  "expected_npv": number;
  "expected_irr": number | null;
  "irr_defined_fraction": number;
  "probability_payout_within_life": number;
  "npv_histogram_data": Array<BinData>;
  "irr_histogram_data": Array<BinData>;
  "capital_at_risk": number;
  "risk_reward_ratio": number;
  "annual_cash_flows_p10": Array<number>;
  "annual_cash_flows_p50": Array<number>;
  "annual_cash_flows_p90": Array<number>;
  "sample_npvs": Array<number>;
};

export type TornadoResult = {
  "base_case_npv": number;
  "sensitivities": Array<SensitivityItem>;
};
